modLoader="javafml"
loaderVersion="[28,)"
# issueTrackerURL="http://my.issue.tracker/"
[[mods]]
modId="nuwa"
version="${file.jarVersion}"
displayName="Nuwa"
#updateJSONURL="http://myurl.me/"
#displayURL="http://example.com/"
logoFile="logo.png"
#credits=""
authors="ZeAmateis, jglrxavpok"
description='''A Minecraft mod that allow you to create content packs and add a tons of new objects without any lines of code !'''

[[dependencies.nuwa]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.nuwa]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"